### ISSUE TITLE
Port domain system example from Python to Go

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go-sc-wrkshp#1]
https://github.com/CityOfZion/python-smart-contract-workshop/blob/master/4-domain.py
Test it to compile with neo-go compiler and run on various nodes, including neo-go.

**Comment by volekerb** [comment]
Converted.
But we have problems with calling `util.FromAddress(owner)`. As of now we don't have proper solution for that.
`CheckWitness(b []byte)` required bytes (hash or key) but we got `string` as input and can't find a good way to convert it in runtime. 
Decided not to push `4-domain.go` example.

**Comment by roman-khimov** [comment]
I think we're gonna be able to port it with the new neo-go invoker that can convert addresses into hash160 before invoking the script (as in nspcc-dev/neo-go#521).

**Comment by volekerb** [comment]
True, will do
